# Generated by Django 2.0.13 on 2019-04-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='student',
        ),
        migrations.RemoveField(
            model_name='labinfo',
            name='user',
        ),
    ]
