# Generated by Django 2.0.13 on 2019-04-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_labinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
