# Generated by Django 2.2 on 2019-04-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_classinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='account_labinfo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
