# Generated by Django 2.2 on 2019-04-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_classinfo_account_labinfo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classinfo',
            old_name='account_labinfo_id',
            new_name='account_classinfo_id',
        ),
    ]
